yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechViews.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    path("group/<slug:slug>/", views.group_posts, name="group"),
    path("new/", views.new_post, name="new_post"),
    path("follow/", views.follow_index, name="follow_index"),
    path("<str:username>/", views.profile, name="profile"),
    path("<str:username>/<int:post_id>/", views.post_view, name="post_view"),
    path("<str:username>/<int:post_id>/edit/",
         views.post_edit, name='post_edit'),
    path("<str:username>/<int:post_id>/comment/",
         views.add_comment, name="add_comment"),
    path("<str:username>/follow/",
         views.profile_follow, name="profile_follow"),
    path("<str:username>/unfollow/",
         views.profile_unfollow, name="profile_unfollow"),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500  # noqa
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'posts.views.page_not_found'  # noqa
handler500 = 'posts.views.server_error'  # noqa

urlpatterns = [
    path("admin/", admin.site.urls),
    path("about/", include("about.urls", namespace="about")),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("", include("posts.urls", namespace="posts")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        verbose_name="Название группы", max_length=200,
        help_text=(
            "В названии группы не "
            "должно содержаться "
            "нецензурной лексики "
            "и словосочетаний, "
            "призывающих к конфликту с другими"
            " группами лиц. "
            "Уместите название в 200 символов"
        )
    )
    slug = models.SlugField(
        verbose_name="URL группы", unique=True,
        help_text="Формируется автоматически"
    )
    description = models.TextField(
        verbose_name="Описание",
        help_text=(
            "Ограничений по символам нет, "
            "в остальном обратите внимание"
            " на указания в формировании названия группы"
        )
    )

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name="Текст публикации",
        help_text=(
            "Постарайтесь не использовать "
            "нецензурную лексику,"
            "задевать власть, национальные "
            "меньшинства и "
            "других представителей флоры и фауны"
        )
    )
    pub_date = models.DateTimeField(
        "Дата публикации", auto_now_add=True,
        help_text=(
            "Дата публикации "
            "формируется автоматически"
        ),
        db_index=True
    )
    group = models.ForeignKey(
        Group, related_name="posts",
        on_delete=models.SET_NULL, blank=True, null=True,
        verbose_name="Группа",
        help_text=(
            "Укажите группу из предложенных,"
            " где опубликуется пост"
        )
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="posts",
        verbose_name="Автор", help_text="Автор - это вы"
    )
    image = models.ImageField(
        upload_to='posts/', verbose_name="Изображение", blank=True, null=True,
        help_text="Можете добавить изображение"
    )

    class Meta:
        ordering = ["-pub_date"]

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="comments",
        verbose_name="Комментированный пост",
        help_text="Можете добавить комментарий"
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE,
        related_name="comments", verbose_name="Автор",
        help_text="Автор комментария - это вы"
    )
    text = models.TextField(
        verbose_name="Комментарий",
        help_text="Здесь вы можете написать все, что думаете"
    )
    created = models.DateTimeField(
        verbose_name="Дата создания комментария", auto_now_add=True,
        help_text="Дата формируется автоматически", db_index=True
    )

    class Meta:
        ordering = ["-created"]

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="follower",
        verbose_name="Подписчик",
        help_text="Этот пользователь подписан на автора"
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="following",
        verbose_name="Автор", help_text="Ваша подписка"
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique_following'
            )
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        error_messages = {
            'text': {
                'required': 'В поле текста должна быть хотя бы одна буква...',
            }
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        error_messages = {
            'text': {
                'required': 'В поле текста должна быть хотя бы одна буква...',
            }
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User

POSTS_ON_PAGE = 10


def index(request):
    posts = Post.objects.all()
    paginator = Paginator(posts, POSTS_ON_PAGE)
    page_num = request.GET.get("page")
    page = paginator.get_page(page_num)
    return render(
        request, "posts/index.html",
        {"page": page}
    )


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, POSTS_ON_PAGE)
    page_num = request.GET.get("page")
    page = paginator.get_page(page_num)
    return render(
        request,
        "group.html",
        {"group": group, "page": page}
    )


@login_required
def new_post(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect("posts:index")

    return render(
        request, "posts/new_post.html",
        {"form": form, "create": True}
    )


def profile(request, username):
    user = get_object_or_404(User, username=username)
    posts = user.posts.all()
    num = posts.count()
    followers = user.following.count()
    follows = user.follower.count()
    following = (request.user.is_authenticated
                 and Follow.objects.filter(author=user,
                                           user=request.user).exists())
    paginator = Paginator(posts, POSTS_ON_PAGE)
    page_num = request.GET.get("page")
    page = paginator.get_page(page_num)
    return render(
        request, "posts/profile.html", context={
            "author": user, "num_of_posts": num,
            "page": page, "following": following,
            "followers": followers, "follows": follows
        }
    )


@login_required
def post_edit(request, username, post_id):
    post = get_object_or_404(
        Post,
        pk=post_id,
        author__username=username
    )
    if request.user.username != username:
        return redirect("posts:post_view", post_id=post_id, username=username)
    form = PostForm(
        request.POST or None, files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect("posts:post_view", post_id=post_id, username=username)
    return render(request, "posts/new_post.html", {"form": form, 'post': post})


@login_required
def add_comment(request, username, post_id):
    post = get_object_or_404(Post, pk=post_id, author__username=username)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect("posts:post_view", post_id=post_id, username=username)


def post_view(request, username, post_id):
    post = get_object_or_404(Post, pk=post_id, author__username=username)
    num = post.author.posts.count()
    followers = post.author.following.count()
    follows = post.author.follower.count()
    comments = post.comments.all()
    form = CommentForm(request.POST or None)
    return render(
        request, "posts/post.html", context={
            "author": post.author, "num_of_posts": num,
            "post": post, "comments": comments, 'form': form, "on_post": True,
            "followers": followers, "follows": follows
        }
    )


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(posts, POSTS_ON_PAGE)
    page_num = request.GET.get("page")
    page = paginator.get_page(page_num)
    return render(
        request,
        "posts/follow.html", {"page": page}
    )


@login_required
def profile_follow(request, username):
    follow_author = get_object_or_404(User, username=username)
    if request.user != follow_author:
        Follow.objects.get_or_create(author=follow_author, user=request.user)
    return redirect("posts:profile", username=username)


@login_required
def profile_unfollow(request, username):
    unfollow_author = get_object_or_404(User, username=username)
    if request.user != unfollow_author:
        unfollow = Follow.objects.filter(
            user=request.user, author=unfollow_author
        )
        unfollow.delete()
    return redirect("posts:profile", username=username)


def page_not_found(request, exception):
    return render(
        request,
        "misc/404.html",
        {"path": request.path},
        status=404
    )


def server_error(request):
    return render(request, "misc/500.html", status=500)

yatube/posts/templates/includes/author_card.html
<div class="card">
    <div class="card-body">
        <div class="h2">
            {{ author.get_full_name }}
        </div>
        <div class="h3 text-muted">
            @{{ author.username }}
        </div>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <div class="h6 text-muted">
                Подписчиков: {{ followers }} <br/>
                Подписан: {{ follows }}
            </div>
        </li>
        <li class="list-group-item">
            <div class="h6 text-muted">
                Записей: {{ num_of_posts }}
            </div>
        </li>
    </ul>
</div>

yatube/posts/templates/includes/author_post.html
<div class="card mb-3 mt-1 shadow-sm">
    {% load thumbnail %}
    {% thumbnail post.image "960x350" crop="60% top" upscale=True as im %}
    <img class="card-img" src="{{ im.url }}">
    {% endthumbnail %}
    <div class="card-body">
        <p class="card-text">
            <a href="{% url 'posts:profile' post.author.username %}">
                <strong class="d-block text-gray-dark">
                    @{{ post.author.username }}
                </strong>
            </a>
            {% if post.group is not null %}
            <a href="{% url 'posts:group' slug=post.group.slug %}">
                <strong class="d-block">
                        Группа: {{ post.group }}
                </strong>
            </a>
            {% endif %}
            {{ post.text }}
        </p>
        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
                {% if user == post.author %}
                <a class="btn btn-sm text-muted" href="{% url 'posts:post_edit' post.author.username post.id %}"
                   role="button">
                    Редактировать
                </a>
                {% endif %}
                {% if not on_post %}
                <a class="btn btn-sm text-muted" href="{% url 'posts:post_view' post.author.username post.pk %}"
                   role="button">
                    Перейти к посту
                </a>
                {% endif %}
            </div>
            <small class="text-muted">{{ post.pub_date|date:"d M Y" }}</small>
        </div>
    </div>
</div>

yatube/posts/templates/includes/comments.html
{% load user_filters %}

{% if user.is_authenticated %}
<div class="card my-3">
    <form method="post" action="{% url 'posts:add_comment' author.username post.id %}">
        {% csrf_token %}
        <h5 class="card-header">Добавить комментарий:</h5>
        {% if form.errors %}
        {% for error in form.errors.values%}
        <div class="alert alert-danger" role="alert">
            {{ error|escape }}
        </div>
        {% endfor %}
        {% endif %}
        <div class="card-body">
            <div class="form-group">
                <div class="form-row">
                    <div class="col">
                        {{ form.text|addclass:"form-control-lg" }}
                    </div>
                    <div class="col">
                        <small class="form-text text-muted">
                            {{ form.text.help_text|safe }}</small>
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
        </div>
    </form>
</div>
{% endif %}

<div class="card my-6">
    <h5 class="card-header">Предыдущие комментарии:</h5>
    {% for item in comments %}
    <!--<div class="media card mb-2">
        <div class="media-body card-body">-->
    <div style="margin-left: 20px">
        <h5 class="mt-2">
            <a href="{% url 'posts:profile' item.author.username %}"
               name="comment_{{ item.id }}">
                {{ item.author.username }}
            </a>
        </h5>
        <p>{{ item.text | linebreaksbr }}</p>
        {% if not forloop.last %}
        <hr>
        {% endif %}
    </div>
    <!--</div>
</div>-->
    {% endfor %}
</div>

yatube/posts/templates/includes/get_follow.html
{% if user.is_authenticated %}
{% if user != author %}
<li class="list-group-item">
    {% if following %}
    <a class="btn btn-lg btn-light"
       href="{% url 'posts:profile_unfollow' author.username %}" role="button">
        Отписаться
    </a>
    {% else %}
    <a class="btn btn-lg btn-primary"
       href="{% url 'posts:profile_follow' author.username %}" role="button">
        Подписаться
    </a>
    {% endif %}
</li>
{% endif %}
{% endif %}

yatube/posts/templates/includes/menu.html
{% if user.is_authenticated %} 
<div class="row">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link {% if index %}active{% endif %}" href="{% url 'posts:index' %}">
        Все авторы
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link {% if follow %}active{% endif %}" href="{% url 'posts:follow_index' %}">
        Избранные авторы
      </a>
    </li>
  </ul>
</div>
{% endif %}