yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechViews.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    path("group/<slug:slug>/", views.group_posts, name="group"),
    path("new/", views.new_post, name="new_post"),
    path("follow/", views.follow_index, name="follow_index"),
    path("<str:username>/", views.profile, name="profile"),
    path("<str:username>/<int:post_id>/", views.post_view, name="post_view"),
    path("<str:username>/<int:post_id>/edit/",
         views.post_edit, name='post_edit'),
    path("<str:username>/<int:post_id>/comment/",
         views.add_comment, name="add_comment"),
    path("<str:username>/follow/",
         views.profile_follow, name="profile_follow"),
    path("<str:username>/unfollow/",
         views.profile_unfollow, name="profile_unfollow"),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500  # noqa
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'posts.views.page_not_found'  # noqa
handler500 = 'posts.views.server_error'  # noqa

urlpatterns = [
    path("admin/", admin.site.urls),
    path("about/", include("about.urls", namespace="about")),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("", include("posts.urls", namespace="posts")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

yatube/templates/base.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %} The Last Social Media You'll Ever Need {% endblock %} | Yatube</title>
    <!-- Загрузка статики -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
</head>

<body>
    {% include 'nav.html' %}
    <main>
        <div class="container">
            <h1>{% block header %}{% endblock %}</h1>
            {% block content %}
            <!-- Содержимое страницы -->
            {% endblock %}
        </div>
    </main>
    {% include 'footer.html' %}
</body>

</html>

yatube/templates/footer.html
<footer class="pt-4 my-md-5 pt-md-3 border-top">
    <p class="m-3 text-dark text-center ">
        <a class="p-2 text-dark" href="{% url 'about:author' %}">Об авторе</a>
        <a class="p-2 text-dark" href="{% url 'about:tech' %}">Технологии</a>
    </p>
    <p class="m-0 text-dark text-center">
        Социальная сеть <span style="color:red">Ya</span>tube © {{ year }} все права защищены</p>
</footer>

yatube/templates/group.html
{% extends "base.html" %}
{% block title %}Записи сообщества{{ group.title }}{% endblock %}
{% block header %}{{ group.title }}{% endblock %}
{% block content %}
<h3>{{group.description}}</h3>
<div class="container">
    {% for post in page %}
    {% include "includes/author_post.html" with post=post %}
    {% endfor %}
</div>
{% if page.has_other_pages %}
{% include "padginator.html" %}
{% endif %}
{% endblock %}

yatube/templates/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="{% url 'posts:index' %}"><span style="color:red">Ya</span>tube</a>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
            Пользователь: {{ user.username }}.
            <a class="p-2 text-dark" href="{% url 'posts:new_post' %}">Новый пост</a>
            <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
            <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
        {% else %}
            <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
            <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
        {% endif %}
    </nav>
</nav>

yatube/templates/padginator.html
{# Отрисовываем навигацию паджинатора только если есть и другие страницы #}
{% if page.has_other_pages %}
<nav>
    <ul class="pagination">
        {% if page.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">&laquo; Предыдущая</span>
        </li>
        {% endif %}
        {% for i in page.paginator.page_range %}
        {% if page.number == i %}
        <li class="page-item active">
          <span class="page-link">{{ i }}
            <span class="sr-only">(текущая)</span>
          </span>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
        {% endif %}
        {% endfor %}
        {% if page.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">Следующая &raquo;</span>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}